### ISSUE TITLE
Set up logging for release version

### ISSUE THREAD

**Issue by daniel-luper** [CS-Journeys/hands-free-chess#53]
**TODO:** 
- [x] Only include error + fatal messages in console logging
- [x] Remove automatic FTP uploading
- [x] Set default log location to "Documents/Hands-Free Chess/log" on Windows
- [x] Cleaner log deletion

**Comment by daniel-luper** [comment]
Done.
